### ISSUE TITLE
doesn't work with nested block sequences

### ISSUE THREAD

**Issue by ezpuzz** [Einenlum/yaml-revealer#4]
I'd like to keep contributing to this plugin, I think a new feature that would be nice is working within a nested block sequence like:
```yaml
this:
  tests:
    - block
    - sequences:
        like: this
```

on last line would expect `this > tests > sequences` but hangs.

on my #3 PR it does not crash but only gets `this > tests`
