### ISSUE TITLE
Add a way of searching for keys in lists

### ISSUE THREAD

**Issue by einenlum** [Einenlum/yaml-revealer#7]
Right now for the following yaml file:

```yaml
monolog:
  channels:
    - foo
    - bar
```
It prints `monolog > channels[]`. But we cannot search for `monolog > channels[] > bar` for example.
